apiVersion: v1
kind: Secret
metadata:
  name: credentials
  labels:
{{ include "photoprism.labels" . | indent 4 }}
stringData:
  PHOTOPRISM_DATABASE_DSN: {{ include "photoprism.databaseDSN" . }}
  PHOTOPRISM_ADMIN_PASSWORD: {{ .Values.adminPassword | default "photoprism" | quote }}
